### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MangaD** [k0ekk0ek/cmake-sphinx#1]
Hello, I would like to use the `cmake/Modules/FindSphinx.cmake` file on my project (public domain). May I know which license is this file using?

**Comment by k0ekk0ek** [comment]
Hi @MangaD! Nice to know someone finds this useful :slightly_smiling_face: I've added a `LICENSE` file and chose `BSD-3-Clause`.

**Comment by MangaD** [comment]
Thank you @k0ekk0ek! I will update my project's license file to reflect your license. :)
